In [226]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(29)

1. How likely is it that you roll doubles when rolling two dice?

In [227]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [2, 5],
       [1, 4],
       [4, 6]])

In [228]:
(pd.DataFrame(rolls)
 .apply(lambda row: row[0]== row[1],axis=1).mean())


0.1709

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [415]:
n_trials = nrows = 10_000
n_flip = ncols = 8

flips = np.random.choice(2, nrows * ncols).reshape(nrows, ncols)
flips

array([[1, 1, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 0, 0],
       [1, 1, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 1, 0]])

In [416]:
# the probability of getting exactly 3 heads

(pd.DataFrame(flips)
 .apply(lambda row: row.values.sum()==3, axis=1).mean())

0.2174

In [233]:
# the probability of getting more than 3 heads?

(pd.DataFrame(flips)
 .apply(lambda row: row.values.sum()>3, axis=1).mean()) 

0.6423

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [524]:
p_data_science = 1

n_billboard = ncols = 2
n_trials = nrows = 10_000

data = np.random.choice(4,nrows * ncols).reshape(nrows, ncols)
data

array([[2, 1],
       [0, 2],
       [0, 2],
       ...,
       [1, 0],
       [2, 1],
       [3, 0]])

In [525]:
(pd.DataFrame(data)
 .apply(lambda row: row[0]== row[1] == 1,axis=1).mean())

0.0626

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [440]:
# each day, avg 3 poptart
# number of poptart = 17,  on Monday
# days  = 4 , on Friday

n_poptart = ncols = 5
n_trials = nrows = 10_000

data = np.random.normal(3,1.5, nrows * ncols).reshape(nrows, ncols)
data


array([[1.73235497, 4.61602395, 2.92027431, 3.66561798, 4.14096827],
       [0.71316809, 2.47558408, 4.19410198, 4.25057987, 4.7634395 ],
       [4.63575585, 2.89056491, 2.51988969, 4.46387699, 1.66020255],
       ...,
       [1.90492544, 2.43942133, 2.20094061, 1.82354242, 4.60462191],
       [6.24245717, 2.5039856 , 1.29547142, 3.94791983, 4.93582173],
       [4.48377966, 4.18498326, 3.49257189, 3.38791367, 6.44919044]])

In [443]:
poptarts_per_week = data.sum(axis=1)
(poptarts_per_week < 16).mean()

0.6289

In [441]:
(pd.DataFrame(data)
 .apply(lambda row: row.values.sum()< 16, axis=1).mean())


0.6289

5. Compare Heights
  - Men have an average height of 178 cm and standard deviation of 8cm. 
  - Women have a mean of 170, sd = 6cm.
  - Since you have means and standard deviations, you can use np.random.normal to generate observations.
  - If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [236]:
n_height = ncols = 1
n_trails = nrows = 10_000

man_height = np.random.normal(178, 8, nrows * ncols).reshape(nrows, ncols)
man_height

array([[180.52404019],
       [190.84381374],
       [170.47132543],
       ...,
       [183.78366938],
       [184.33659627],
       [157.10486396]])

In [237]:
woman_height = np.random.normal(170, 6, nrows * ncols).reshape(nrows, ncols)
woman_height

array([[174.76405932],
       [169.45288291],
       [168.6452196 ],
       ...,
       [167.59030253],
       [169.20912114],
       [162.89597937]])

In [238]:
(woman_height > man_height).mean()

0.2143

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

    What is the probability that we observe an installation issue within the first 150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?

In [464]:
# ----solution------

outcomes = ['S', 'F']
n_students = 50
n_trials = 10_000
data = np.random.choice(outcomes, size= (n_trials, n_students), p=[1/250, 249/250]).reshape(n_trials, n_students)
data

array([['F', 'F', 'F', ..., 'F', 'F', 'F'],
       ['F', 'F', 'F', ..., 'F', 'F', 'F'],
       ['F', 'F', 'F', ..., 'F', 'F', 'F'],
       ...,
       ['F', 'F', 'F', ..., 'F', 'F', 'F'],
       ['F', 'F', 'F', ..., 'F', 'F', 'F'],
       ['F', 'F', 'F', ..., 'F', 'S', 'F']], dtype='<U1')

In [471]:
(data == 'S').sum(axis=1)


array([0, 0, 0, ..., 0, 1, 1])

In [472]:
((data == 'S').sum(axis=1)== n_students).mean()

0.0

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

    How likely is it that a food truck will show up sometime this week?

<!-- # If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40? -->

In [479]:
p_truck = .7  #  probability of a food truck present at Travis Park on any given day
p_no_truck = .3  #  probability of a food truck absent at Travis Park on any given day

n_days_without_truck = ncols = 3
n_trials = nrows = 10_000

data = np.random.random((nrows, ncols))
data


array([[0.11063663, 0.62541093, 0.67517752],
       [0.55779137, 0.0515499 , 0.95436534],
       [0.11494852, 0.33522784, 0.01551747],
       ...,
       [0.19343678, 0.46662778, 0.16402172],
       [0.39186969, 0.73717663, 0.23827296],
       [0.97462004, 0.47392644, 0.58148796]])

In [480]:
(data > p_truck).sum(axis=1)

array([0, 1, 0, ..., 0, 1, 1])

In [481]:
(data > p_truck).sum(axis=1)>3

array([False, False, False, ..., False, False, False])

In [493]:
((data > p_truck).sum(axis=1)==3).mean()

0.0264

In [491]:
((data < p_truck).sum(axis=1)>=1).mean()

0.9736

In [458]:
# ---------solution----------

# 0 = no trucks, 1 = truck show up
outcomes = [0,1]
n_days = 3
n_trials = 10_000
trucks = np.random.choice([0,1], size= (n_trials, n_days), p=[.3, .7]).reshape(n_trials, n_days)
trucks


array([[1, 1, 1],
       [1, 0, 1],
       [0, 1, 0],
       ...,
       [0, 0, 1],
       [1, 1, 0],
       [0, 0, 1]])

In [469]:
trucks.sum(axis=1)

array([3, 2, 1, ..., 1, 2, 1])

In [470]:
(trucks.sum(axis=1)==0).mean()

0.0292

In [461]:
(trucks.sum(axis=1)>=1).mean()

0.9708

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [ ]:
#---solution ---

In [510]:
#number of days in a year
outcomes = range(0, 365) 

n_students= 23 #number of students

n_simulations = 10000

In [519]:
#using random choice to get the possible birthdays
birthdays= np.random.choice(outcomes, size=(n_simulations, n_students))

birthdays

array([[250,  49,  39, ..., 302, 314, 127],
       [ 71, 226, 173, ...,   5, 115, 320],
       [211,  26, 336, ...,  48, 125, 143],
       ...,
       [269, 257, 154, ..., 186, 176, 261],
       [243,  17,   0, ...,  71, 322, 236],
       [255, 289,  80, ..., 166,  18,  32]])

In [520]:
#turn it into a DF so it's easier to read
birthdays = pd.DataFrame(birthdays)

birthdays.head()

0    1    2    3    4    5    6    7    8    9   ...   30   31   32   33  \
0  250   49   39  219   33   65  275    3   43  287  ...  151  257   79  241   
1   71  226  173  209  318   11  150  261  139  293  ...   49   39   95  305   
2  211   26  336  219  221   36  303  212   72    9  ...   37  284  170  231   
3   53  291  290  191  151  215  361  145  172  208  ...   17  215  312  126   
4   61  305  205  270  327   57  291  324  104  249  ...  324  251  157  211   

    34   35   36   37   38   39  
0   97  347   87  302  314  127  
1  205  360  113    5  115  320  
2   43  358  283   48  125  143  
3  177   49  157  146  215  250  
4  273  178   89  258  269  156  

[5 rows x 40 columns]

In [512]:
# For 23 people, what are the odds that two of them share a birthday? 

(birthdays.nunique(axis=1) < 23).mean()

0.5055

In [521]:
# For 20 people, what are the odds that two of them share a birthday?

n_students = 20
birthdays= np.random.choice(outcomes, size=(n_simulations, n_students))

birthdays = pd.DataFrame(birthdays)
(birthdays.nunique(axis=1) < n_students).mean()

0.413

In [518]:
# For 40 people, what are the odds that two of them share a birthday?

n_students = 40
birthdays= np.random.choice(outcomes, size=(n_simulations, n_students))

birthdays = pd.DataFrame(birthdays)
(birthdays.nunique(axis=1) < n_students).mean()

0.8894