In [75]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


import viz # curriculum example visualizations

np.random.seed(29)


1. How likely is it that you roll doubles when rolling two dice?

In [3]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 3],
       [4, 5],
       [3, 5],
       ...,
       [2, 2],
       [1, 5],
       [3, 1]])

In [16]:
(pd.DataFrame(rolls)
 .apply(lambda row: row[0]== row[1],axis=1).mean())


0.1628

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [23]:
n_trials = nrows = 10_000
n_flip = ncols = 8

flips = np.random.choice(2, n_trials * n_dice).reshape(nrows, ncols)
flips

array([[0, 0, 1, ..., 1, 0, 1],
       [1, 1, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 1, 0, 0]])

In [29]:
# the probability of getting exactly 3 heads

(pd.DataFrame(flips)
 .apply(lambda row: row.values.sum()==3, axis=1).mean())

0.2214

In [30]:
# the probability of getting more than 3 heads?

(pd.DataFrame(flips)
 .apply(lambda row: row.values.sum()>3, axis=1).mean()) 

0.6325

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [151]:
p_data_science = 1  #. probability of selecting data science cohort

n_billboard = ncols = 2
n_trials = nrows = 10_000

data = np.random.choice(4,nrows * ncols).reshape(nrows, ncols)
data

array([[0, 1],
       [2, 0],
       [1, 2],
       ...,
       [3, 0],
       [1, 1],
       [0, 0]])

In [52]:
(pd.DataFrame(data)
 .apply(lambda row: row[0]== row[1] == 1,axis=1).mean())

0.0616

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [59]:
# each day, avg 3 poptart
# number of poptart = 17,  on Monday
# days  = 4 , on Friday

n_poptart = ncols = 4
n_trials = nrows = 10_000

data = np.random.normal(3,1.5, nrows * ncols).reshape(nrows, ncols)
data


array([[5.41822074, 2.02509321, 4.38569585, 7.1646236 ],
       [5.06548474, 4.09813015, 1.89641697, 2.7837691 ],
       [2.65367079, 3.97113847, 1.74842608, 3.22657456],
       ...,
       [1.8074832 , 5.25035243, 5.20160423, 2.69719383],
       [4.97934923, 3.58533556, 2.9934409 , 2.18214437],
       [4.41301036, 4.12815557, 0.65473347, 0.1376184 ]])

In [89]:
(pd.DataFrame(data)
 .apply(lambda row: row.values.sum()<(1/17), axis=1).mean())


0.0001

5. Compare Heights
  - Men have an average height of 178 cm and standard deviation of 8cm. 
  - Women have a mean of 170, sd = 6cm.
  - Since you have means and standard deviations, you can use np.random.normal to generate observations.
  - If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [64]:
n_height = ncols = 1
n_trails = nrows = 10_000

man_height = np.random.normal(178, 8, nrows * ncols).reshape(nrows, ncols)
man_height

array([[188.41448163],
       [193.97153301],
       [176.74767992],
       ...,
       [171.55040906],
       [161.12261756],
       [191.92800807]])

In [65]:
woman_height = np.random.normal(170, 6, nrows * ncols).reshape(nrows, ncols)
woman_height

array([[170.54372127],
       [165.73296516],
       [166.36132251],
       ...,
       [163.06740722],
       [161.4182784 ],
       [160.81303866]])

In [155]:
(woman_height > man_height).mean()

0.2161

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

    What is the probability that we observe an installation issue within the first 150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?

In [216]:
p_installation_fail = 1/250
p_installation_success = 249/250

ncols = 1
nrows = 10_000

data = np.random.random((nrows, ncols))
data



array([[0.74855752],
       [0.47391252],
       [0.76918295],
       ...,
       [0.48479528],
       [0.93285992],
       [0.61647907]])

In [218]:

(pd.DataFrame(data)
 .apply(lambda row: row.values > (1/250)* 50).sum(axis=1).mean())

0.7997

In [219]:
(pd.DataFrame(data)
 .apply(lambda row: row.values > (1/250)* 100).sum(axis=1).mean())

0.6018

In [221]:
(pd.DataFrame(data)
 .apply(lambda row: row.values < (1/250)* 150).sum(axis=1).mean())

0.5921

In [222]:
(pd.DataFrame(data)
 .apply(lambda row: row.values < (1/250)* 450).sum(axis=1).mean())

1.0

In [189]:
ncols = 100
nrows = 10_000
data = np.random.random((nrows, ncols))
data


array([[0.24771566, 0.81548919, 0.10741276, ..., 0.26117463, 0.6523691 ,
        0.68243057],
       [0.65451722, 0.96988021, 0.38383672, ..., 0.2307404 , 0.88555304,
        0.16470616],
       [0.8623366 , 0.3802841 , 0.79076283, ..., 0.62037852, 0.59619359,
        0.36803281],
       ...,
       [0.04739318, 0.67383319, 0.71291694, ..., 0.8313982 , 0.87884641,
        0.90537531],
       [0.39613804, 0.5653801 , 0.30061853, ..., 0.90575957, 0.78538107,
        0.96780902],
       [0.15381812, 0.39078776, 0.90137426, ..., 0.43912546, 0.49482485,
        0.33469846]])

In [211]:
(pd.DataFrame(data)
 .apply(lambda row: row.values > p_installation_fail).sum(axis=1).mean())

99.594

In [201]:
ncols = 100
nrows = 10_000
data = np.random.random((nrows, ncols))
data

array([[0.29424718, 0.2885849 , 0.86281458, ..., 0.07414573, 0.73274695,
        0.49470294],
       [0.53340994, 0.19822676, 0.42520711, ..., 0.1196712 , 0.86789901,
        0.56175688],
       [0.36191879, 0.06579903, 0.75353766, ..., 0.03741123, 0.50940295,
        0.92504184],
       ...,
       [0.65651213, 0.85945975, 0.68344581, ..., 0.67118712, 0.75998461,
        0.31410818],
       [0.09711309, 0.42736532, 0.02159681, ..., 0.30397706, 0.67744593,
        0.8603748 ],
       [0.76669071, 0.26445713, 0.83285133, ..., 0.18295814, 0.89666695,
        0.29885198]])

In [202]:
(pd.DataFrame(data)
 .apply(lambda row: row.values < p_installation_fail).sum(axis=1).mean())

0.4075

In [203]:
ncols = 450
nrows = 10_000
data = np.random.random((nrows, ncols))
data

array([[0.37951524, 0.77835806, 0.59986975, ..., 0.4647389 , 0.35401831,
        0.91337184],
       [0.85550522, 0.1990643 , 0.44461905, ..., 0.31236468, 0.00829659,
        0.33511564],
       [0.12840438, 0.82120997, 0.18001747, ..., 0.67280012, 0.7309798 ,
        0.50240386],
       ...,
       [0.19751236, 0.56174009, 0.09327568, ..., 0.07367598, 0.93292059,
        0.02572691],
       [0.78224746, 0.57314404, 0.04735993, ..., 0.49210388, 0.2920506 ,
        0.27613784],
       [0.20645797, 0.71428419, 0.16291744, ..., 0.54255161, 0.43344815,
        0.59244447]])

In [210]:
(pd.DataFrame(data)
 .apply(lambda row: row.values > p_installation_fail).sum(axis=1).mean())

0.406

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

    How likely is it that a food truck will show up sometime this week?

<!-- # If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40? -->

In [148]:
p_truck = .7  #  probability of a food truck present at Travis Park on any given day
p_no_truck = .3  #  probability of a food truck absent at Travis Park on any given day

n_days_without_truck = ncols = 3
n_trials = nrows = 10_000

data = np.random.random((nrows, ncols))
data


array([[0.99674913, 0.83427989, 0.26107082],
       [0.58012672, 0.4503099 , 0.43264922],
       [0.73513937, 0.00421607, 0.9585584 ],
       ...,
       [0.27565242, 0.46561256, 0.4991321 ],
       [0.48548991, 0.22321908, 0.86783577],
       [0.24904338, 0.53279851, 0.66423149]])

In [179]:
data < p_truck

array([[False,  True],
       [ True, False],
       [ True,  True],
       ...,
       [ True, False],
       [ True,  True],
       [False, False]])

In [186]:
(data < p_no_truck).sum(axis=1)

array([1, 1, 0, ..., 1, 0, 2])

In [183]:
(data < p_truck).sum(axis=1).mean()

0.4982

In [185]:

(pd.DataFrame(data)
 .apply(lambda row: row.values < p_no_truck).sum(axis=1).mean())

0.4982

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [130]:
n_share_birthday = ncols = 2
n_trials = nrows = 10_000

data = np.random.random((nrows, ncols))
data

array([[0.00195361, 0.15699442],
       [0.05630093, 0.2728512 ],
       [0.04130166, 0.67146318],
       ...,
       [0.47767834, 0.84645793],
       [0.1284385 , 0.60463806],
       [0.195951  , 0.70279102]])

In [135]:
k = data < (2/23)
k

array([[ True, False],
       [ True, False],
       [ True, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [136]:
k.sum(axis=1)

array([1, 1, 1, ..., 0, 0, 0])

In [137]:
k.sum(axis=1).mean()

0.1803

In [141]:
p_share_birthday = n_total = 2/23
(pd.DataFrame(data)
 .apply(lambda row: row.values < n_total_23).sum(axis=1).mean())

0.1803

In [142]:
p_share_birthday = n_total = 2/20
(pd.DataFrame(data)
 .apply(lambda row: row.values < n_total).sum(axis=1).mean())

0.2058

In [143]:
p_share_birthday = n_total = 2/40
(pd.DataFrame(data)
 .apply(lambda row: row.values < n_total).sum(axis=1).mean())

0.1071